server:
    port: 8080
spring:
    application:
        name: API-GATEWAY
    cloud:
        gateway:
            routes:
            -   id: BOOK-SERVICE
                predicates:
                - Path=/book/**
                uri: lb://BOOK-SERVICE
            -   id: AUTHOR-SERVICE
                predicates:
                - Path=/author/**
                uri: lb://AUTHOR-SERVICE
        config:
            import-check:
                enabled: false

logging:
    level:
        org.springframework.cloud.gateway: DEBUG
eureka:
    client:
        serviceUrl:
            defaultZone: http://192.168.32.1:8761/eureka
        registerWithEureka: true
        fetchRegistry: true
    instance:
        leaseRenewalIntervalInSeconds: 30
        preferIpAddress: true
        leaseExpirationDurationInSeconds: 30
management:
    tracing:
        enabled: true
        sampler:
            probability: 1.0
    endpoint:
        info:
            enabled: true
    endpoints:
        web:
            exposure:
                include: '*'
    info:
        env:
            enabled: true