eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    should-unregister-on-shutdown: true
  instance:
    lease-renewal-interval-in-seconds: 30
    preferIpAddress: true
info:
  app:
    version: '@project.version@'
management:
  tracing:
    enabled: true
    sampler:
      probability: 1.0
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
server:
  port: 9191
spring:
  application:
    name: api-gateway
    cloud:
      gateway:
        routes:
          - id: BOOK-SERVICE
            predicates:
              - Path=/book/**
            uri: lb://BOOK-SERVICE
          - id: AUTHOR-SERVICE
            predicates:
              - Path=/author/**
            uri: lb://AUTHOR-SERVICE
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  zipkin:
    base-url: http://localhost:9411
  micrometer:
    enabled: true
